Cache mongo client, not client promise
mongodb-developer/nextjs-with-mongodb pull request #1
Opened 2024-06-06 16:20 UTC by baileympearson

Caching the client's promise can lead to unhandled promise rejections if the client fails to connect.  Caching the client avoids this pitfall.

The mongo client will auto connect on the first operation.

2024-06-06 16:34 UTC, nbbeeken requested changes

2024-06-06 16:34 UTC, nbbeeken commented on pages/index.tsx
> +    // `await client.connect()` will use the default database passed in the MONGODB_URI
I am not sure what it means for connect to "use a database" and the line below still references "clientPromise".

I would uncomment the sample `find` code, just cutting to the chase so to speak.

2024-06-06 16:34 UTC, nbbeeken commented on lib/mongodb.ts
> +    _mongoClient?: MongoClient;
`types/mongodb.d.ts` still references the old global.

Optional, can we use `globlThis` (instead of `global`) here? Sticks out as legacy to me, but not necessary.

2024-06-06 17:53 UTC, Rieranthony commented
Thanks for this guys! Curious to know if you have a solution for people using prisma as ORM with the mongodb driver?

2024-06-07 04:42 UTC, maulikdhameliya commented
Thanks applied the same solution. Will confirm how it goes after observing for a week or so

2024-06-07 10:46 UTC, joellord approved these changes
I tested everything locally and it works. I did not have the 504 errors though, so I can't confirm that it solves that issue. It does not, however, introduce new errors.

2024-06-07 13:01 UTC, merged

2024-06-07 13:17 UTC, maulikdhameliya commented
> I tested everything locally and it works. I did not have the 504 errors though, so I can't confirm that it solves that issue. It does not, however, introduce new errors.

This fix works very well. I have been observing vercel logs for the last 10 hrs for my app and not seeing 500 errors anymore.

2024-06-07 14:37 UTC, baileympearson commented
Hey @Rieranthony - Prisma doesn't actually use the Node driver (see https://github.com/prisma/prisma/discussions/12886).  If you're seeing timeout errors from Prisma, I'd suggest reaching out to them, since they'll be better equipped to troubleshoot.

2025-05-30 03:23 UTC, johnumarattilbb commented
I just updated my code because of the same pattern. Hopefully, this will fix the troublemaker!